{
 "title": "MAAS Site Manager Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } }
  ]
 },
 "panels": [
  { "title": "API Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MAAS Site Manager API Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{pebble_service=\"msm\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\"$juju_unit\"} |= \"\""
    }
   ]
  },
  { "title": "HTTP Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "HTTP Request Bytes per Second",
   "type": "timeseries",
   "description": "The amount of bytes sent per second in HTTP requests, per endpoint",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(http_request_size_bytes_sum[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration per Endpoint, Method (5 min running avg)",
   "type": "timeseries",
   "description": "A 5 minute running average of the time spent per HTTP request, for each endpoint/method",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(http_request_duration_seconds_sum[5m]))",
     "legendFormat": "raw {{handler}} ({{method}}"
    },
    {
     "expr": "sum by(handler, method) (rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "raw {{handler}} ({{method}}) count"
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "HTTP Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 14 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "{{handler}} ({{method}})" }
   ]
  },
  {
   "title": "Percentile of HTTP Request Duration (5 min average)",
   "type": "status-history",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_highr_seconds_bucket[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_highr_seconds_bucket[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_request_duration_highr_seconds_bucket[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_request_duration_highr_seconds_bucket[5m])))",
     "legendFormat": "75th percentile"
    }
   ]
  },
  { "title": "Database Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "DB Query Time per Endpoint, Method (5 min running avg)",
   "type": "timeseries",
   "description": "5 minute running average of time spent on database queries per request handler, method",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(db_queries_duration_seconds_sum{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "raw {{handler}} ({{method}})"
    },
    {
     "expr": "sum by(handler, method) (rate(db_queries_duration_seconds_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "raw {{handler}} count ({{method}})"
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Database Queries per Second",
   "type": "timeseries",
   "description": "The number of database queries done per second by each handler/method",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "q/s" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(db_queries_total{handler!=\"none\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "{{handler}} ({{method}})"
    }
   ]
  },
  {
   "title": "Percentile of Time Spent on DB Queries (5 min average)",
   "type": "status-history",
   "description": "Five-minute running average of the amount of time spent on database queries for x% of requests",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(db_queries_duration_seconds_bucket{handler!=\"none\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(db_queries_duration_seconds_bucket{handler!=\"none\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(db_queries_duration_seconds_bucket{handler!=\"none\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(db_queries_duration_seconds_bucket{handler!=\"none\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m])))",
     "legendFormat": "75th percentile"
    }
   ]
  }
 ]
}