{
 "title": "MAAS Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   { "name": "maas_id", "label": "MAAS ID", "query": { "query": "label_values(maas_id)" } },
   { "name": "node", "query": { "query": "label_values(host)" } },
   { "name": "racks", "query": { "query": "label_values(system_id)" } },
   { "name": "maas_vip", "query": "127.0.0.1" },
   {
    "name": "status_code",
    "query": "400,401,403,404,409,500,501,503"
   }
  ]
 },
 "panels": [
  { "title": "Controllers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Region/Rack Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(maas_nodes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\",type=\"regionracks\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max(maas_nodes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\",type=\"regions\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rack Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "max(maas_nodes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\",type=\"racks\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Racks Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Rack Services Status (system_id=$racks)",
   "type": "stat",
   "description": "Show the rack services that are in a Dead or Degraded status.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "repeat": "racks",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by(service, system_id) (1, sort_desc(maas_service_availability{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\",pid=\"\",system_id=\"$racks\"}) == 2 == 3)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "RPC Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Rack -> Region calls avg latency",
   "type": "timeseries",
   "description": "Average latency of rack to region rpc calls in $__rate_interval interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(call) (rate(maas_rack_region_rpc_call_latency_sum{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval])) / sum by(call) (rate(maas_rack_region_rpc_call_latency_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rack -> Region calls latency",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(call) (rate(maas_rack_region_rpc_call_latency_sum{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval])) / sum by(call) (rate(maas_rack_region_rpc_call_latency_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, call) (rate(maas_rack_region_rpc_call_latency_bucket{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.0001, sum by(call, le) (rate(maas_rack_region_rpc_call_latency_bucket{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])))",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Region -> Rack calls avg latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(call) (rate(maas_region_rack_rpc_call_latency_sum{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval])) / sum by(call) (rate(maas_region_rack_rpc_call_latency_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region -> Rack calls",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(call) (rate(maas_region_rack_rpc_call_latency_sum{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval])) / sum by(call) (rate(maas_region_rack_rpc_call_latency_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, call) (rate(maas_region_rack_rpc_call_latency_bucket{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.0001, sum by(le, call) (rate(maas_region_rack_rpc_call_latency_bucket{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])))",
     "legendFormat": "min"
    }
   ]
  },
  { "title": "API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Machine Listing percentiles (v2)",
   "type": "timeseries",
   "description": "Time necessary to fetch machines through the v2 API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, handler) (rate(maas_apiserver_request_latency_bucket{handler=\"/MAAS/a/v2/machines\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, handler) (rate(maas_apiserver_request_latency_bucket{handler=\"/MAAS/a/v2/machines\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, handler) (rate(maas_apiserver_request_latency_bucket{handler=\"/MAAS/a/v2/machines\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Machine Listing percentiles (WS)",
   "type": "timeseries",
   "description": "Time necessary to fetch machines through websockets. Includes a call to the v2 machine listing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, call) (rate(maas_websocket_call_latency_bucket{call=\"machine.list\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, call) (rate(maas_websocket_call_latency_bucket{call=\"machine.list\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, call) (rate(maas_websocket_call_latency_bucket{call=\"machine.list\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "4xx/5xx responses count (last 30m)",
   "type": "stat",
   "description": "API calls with error status codes, grouped by status code, in the last 30 minutes.\nClick on a value to visualize which API calls are failing.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (round(increase(maas_http_request_latency_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\",status=~\"[4,5][0-9]{2}\"}[30m]), 1))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status) (round(increase(maas_apiserver_request_latency_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\",status=~\"[4,5][0-9]{2}\"}[30m]), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API calls with $status_code response ",
   "type": "stat",
   "description": "Shows which API calls are failing with the specified status code. To modify the visualization (i.e. the status code) use the panel above.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, path) (round(increase(maas_http_request_latency_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\",status=\"$status_code\"}[30m]) > 0, 1))",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "sum by(method, handler) (round(increase(maas_apiserver_request_latency_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\",status=\"$status_code\"}[30m]) > 0, 1))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  { "title": "Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Machines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B - $A", "type": "math" },
    {
     "expr": "max(maas_kvm_machines{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "Virtual"
    },
    {
     "expr": "max(maas_nodes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\",type=\"machines\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 72 },
   "targets": [
    {
     "expr": "max(maas_nodes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\",type=\"devices\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KVM Hosts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 72 },
   "targets": [
    {
     "expr": "max(maas_kvm_pods{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machines by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "max by(status) (maas_machines{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Networks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Spaces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "max(maas_net_spaces{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fabrics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 87 },
   "targets": [
    {
     "expr": "max(maas_net_fabrics{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VLANs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 87 },
   "targets": [
    {
     "expr": "max(maas_net_vlans{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPv4 subnets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "max(maas_net_subnets_v4{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPv6 subnets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 87 },
   "targets": [
    {
     "expr": "max(maas_net_subnets_v6{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPs availability per subnet",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 87 },
   "targets": [
    {
     "expr": "max(maas_net_subnet_ip_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\",status=\"available\"}) by(cidr)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(maas_net_subnet_ip_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\",status=\"unavailable\"}) by(cidr)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "KVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Cores",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "avg by(status) (maas_kvm_cores{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "avg(maas_kvm_overcommit_cores{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "available with vercommit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(status) (maas_kvm_memory{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(maas_kvm_overcommit_memory{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "available with overcommit"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(status) (maas_kvm_storage{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}